#!/bin/bash

source env.list

if [ -z ${PRIVATE_KEY_PATH+x} ]; then
  echo "Error: PRIVATE_KEY_PATH must be set."
  exit 1
fi

# ---- ^ preamble
echo "Decrypting secrets.yaml.enc to secrets.yaml"
openssl enc -d -aes-256-cbc -in secrets.yaml.enc -out secrets.yaml -pass file:${PRIVATE_KEY_PATH}

echo "Done!"
