#!/bin/bash

source env.list

if [ -z ${PRIVATE_KEY_PATH+x} ]; then
  echo "Error: PRIVATE_KEY_PATH must be set."
  exit 1
fi

echo "Encrypting secrets.yaml to secrets.yaml.enc"
openssl enc -aes-256-cbc -salt -in secrets.yaml -out secrets.yaml.enc -pass file:${PRIVATE_KEY_PATH}

echo "Before committing, update .drone.sec by encoding secrets.yaml in the Drone UI: https://drone-general-prd.newsdev.net/nytm/ugc-moderator/settings/encrypt"
